openapi: 3.0.0
info:
  title: Silicon IP API
  description: Silicon IP Information Service
  version: "0.1"
tags:
  - name: Silicon_IP
    description: Silicon IP Product service
  - name: Beta
    description: In development
paths:
  /product/info:
    get:
      description: ""
      operationId: GET /product/info
      tags:
        - Beta
        - Production
      parameters:
        - required: true
          in: query
          name: "product. Eg: USB4"
          schema:
            type: string
      x-kong-plugin-mocking:
        enabled: true
        config:
          api_specification_filename: silicon_ip.yaml    
      x-kong-plugin-openid-connect:
        enabled: true
        config:
          issuer: https://dev-513727.okta.com/oauth2/default
          consumer_optional: true
          verify_parameters: false
          auth_methods:
          - client_credentials
          scopes: []
      x-kong-plugin-rate-limiting:
        enabled: true
        config:
          minute: 5
          limit_by: ip
          policy: local
      responses:
        '200':
          description: ""
          content:
            application/json:
              examples:
                response:
                  value:
                    {
                      "meta_data": {
                          "api_name": "silicon_ip_product_v2",
                          "num_total_data_points": 1,
                          "credit_cost": 10,
                          "start_date": "yesterday",
                          "end_date": "yesterday"
                      },
                      "result_data": {
                          "USB": [
                            {
                                "controllers": "device",
                                "features": "router",
                                "process_tech": "5-6nm-FinFet",
                                "verification_ip": "yes"
                            }
                          ]
                      }
                    }
servers:
  - url: http://mockbin.org/request